### ISSUE TITLE
Can't get attribute '_default_unk_index' when loading glove embed

### ISSUE THREAD

**Issue by wtjiang98** [jamesli1618/Obj-GAN#15]
I am in the image generation step and get the error below:

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jwt/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/jwt/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/data4_ssd/jwt/project/Obj-GAN-master/image_generation/image_generation.py", line 126, in <module>
    dataset = TestDataset(cfg.DATA_DIR, split_dir, base_size=cfg.TREE.BASE_SIZE)
  File "/mnt/data4_ssd/jwt/project/Obj-GAN-master/image_generation/testDataset.py", line 47, in __init__
    self.glove_embed = load_glove_emb(data_dir, split, train_names, test_names)
  File "/mnt/data4_ssd/jwt/project/Obj-GAN-master/image_generation/miscc/load.py", line 395, in load_glove_emb
    x = pickle.load(f)
AttributeError: Can't get attribute '_default_unk_index' on <module 'torchtext.vocab' from '/home/jwt/anaconda3/envs/pytorch4/lib/python3.7/site-packages/torchtext/vocab.py'>

It seems that when loading the 'captions_glove.pickle' download from [coco](https://drive.google.com/open?id=1GbZESaDwkpV8gH2gyo1bUogPtYu1QEPF), there miss an attribute '_default_unk_index'.

When I want to generate the 'captions_glove.pickle' by myself, there miss an parameter in line 383, 384 in image_generation/miscc/load.py. See detail below:
`train_captions = load_captions(data_dir, train_names)`
where the parameter 'embeddings_num' is missed.

I am wondering is the downloaded 'captions_glove.pickle' broken? And what should I set to the parameter 'embeddings_num'?

Thanks.

**Comment by wtjiang98** [comment]
Problem solved by using python3.6, using python3.7 will cause this error.

**Comment by wtjiang98** [comment]
Using python3.6 still has this error...

**Comment by wtjiang98** [comment]
I generated the glove embed by myself, using embeddings_num=5 for coco.
