### ISSUE TITLE
one issue in datasets.py

### ISSUE THREAD

**Issue by cn-boop** [jamesli1618/Obj-GAN#20]
when I run datasets.py in the shape_generation folder,I have a bug :
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    base_size=cfg.TREE.BASE_SIZE)
  File "/home/cn/Obj-GAN/shape_generation/datasets.py", line 143, in __init__
    self.img_bytes = self.load_imgs_data(data_dir, split)
  File "/home/cn/Obj-GAN/shape_generation/datasets.py", line 241, in load_imgs_data
    img_bytes = self.read_imgs(data_dir, filenames, filepath)
  File "/home/cn/Obj-GAN/shape_generation/datasets.py", line 224, in read_imgs
    img_bytes_len = struct.unpack('i', fid.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes
I think its because train_imgs.bigfile is empty,so why and how can solve this problem?

**Comment by SreeHarshaNelaturu** [comment]
I'm facing this error as well, did you find any fix?

**Comment by Williamwsk** [comment]
I also had the same problem, did you solve it?

**Comment by ctttt1119** [comment]
I also had the same problem, did you solve it?

**Comment by Ermonitory** [comment]
Just delete the 'train_imgs.bigfile' and train it again will solve this problem.

**Comment by raven0327** [comment]
or try to delete "test_imgs.bigfile"
